services:
  mysql:
    image: mysql:8.4
    mem_limit: 300m
    cpus: 0.5
    container_name: engdu-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=+09:00
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - engdu

  nginx:
    image: nginx:1.24.0
    mem_limit: 100m
    cpus: 0.2
    container_name: engdu-nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro

    networks:
      - engdu

volumes:
  mysql_data:

networks:
  engdu:
    name: engdu-network