# 도커 컴포즈는 하나의 컨테이너를 서비스라 부른다.
services:
  my-server:
    build: . #현재 파일 경로의 도커파일을 빌드하겠다.
    container_name: my-server
    volumes:
      - ./logs:/logs
    ports:
      - 8080:8080
    env_file:
      - .env

  promtail:
    image: grafana/promtail:latest
    env_file:
      - .env
    volumes:
      # 로그 읽기 위치를 기록하는 파일을 위해 볼륨 설정 (재시작 시 중복 방지)
      - /tmp/positions:/tmp/positions
      - ./logs:/logs
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true