spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    com.gyu.engdu: DEBUG
    org.springframework: INFO
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF